<?php

declare(strict_types=1);

namespace Atendwa\Msingi\Database\Seeders;

use Atendwa\Msingi\Models\Country;
use Atendwa\Seedtrack\Concerns\PreventsDuplicateSeeding;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    use PreventsDuplicateSeeding;

    public function execute(): void
    {
        $europeanCountries = [
            ['name' => 'Albania', 'continent' => 'Europe', 'short_code' => 'AL', 'flag' => '🇦🇱'],
            ['name' => 'Andorra', 'continent' => 'Europe', 'short_code' => 'AD', 'flag' => '🇦🇩'],
            ['name' => 'Armenia', 'continent' => 'Europe', 'short_code' => 'AM', 'flag' => '🇦🇲'],
            ['name' => 'Austria', 'continent' => 'Europe', 'short_code' => 'AT', 'flag' => '🇦🇹'],
            ['name' => 'Azerbaijan', 'continent' => 'Europe', 'short_code' => 'AZ', 'flag' => '🇦🇿'],
            ['name' => 'Belarus', 'continent' => 'Europe', 'short_code' => 'BY', 'flag' => '🇧🇾'],
            ['name' => 'Belgium', 'continent' => 'Europe', 'short_code' => 'BE', 'flag' => '🇧🇪'],
            ['name' => 'Bosnia and Herzegovina', 'continent' => 'Europe', 'short_code' => 'BA', 'flag' => '🇧🇦'],
            ['name' => 'Bulgaria', 'continent' => 'Europe', 'short_code' => 'BG', 'flag' => '🇧🇬'],
            ['name' => 'Croatia', 'continent' => 'Europe', 'short_code' => 'HR', 'flag' => '🇭🇷'],
            ['name' => 'Cyprus', 'continent' => 'Europe', 'short_code' => 'CY', 'flag' => '🇨🇾'],
            ['name' => 'Czech Republic', 'continent' => 'Europe', 'short_code' => 'CZ', 'flag' => '🇨🇿'],
            ['name' => 'Denmark', 'continent' => 'Europe', 'short_code' => 'DK', 'flag' => '🇩🇰'],
            ['name' => 'Estonia', 'continent' => 'Europe', 'short_code' => 'EE', 'flag' => '🇪🇪'],
            ['name' => 'Finland', 'continent' => 'Europe', 'short_code' => 'FI', 'flag' => '🇫🇮'],
            ['name' => 'France', 'continent' => 'Europe', 'short_code' => 'FR', 'flag' => '🇫🇷'],
            ['name' => 'Georgia', 'continent' => 'Europe', 'short_code' => 'GE', 'flag' => '🇬🇪'],
            ['name' => 'Germany', 'continent' => 'Europe', 'short_code' => 'DE', 'flag' => '🇩🇪'],
            ['name' => 'Greece', 'continent' => 'Europe', 'short_code' => 'GR', 'flag' => '🇬🇷'],
            ['name' => 'Hungary', 'continent' => 'Europe', 'short_code' => 'HU', 'flag' => '🇭🇺'],
            ['name' => 'Iceland', 'continent' => 'Europe', 'short_code' => 'IS', 'flag' => '🇮🇸'],
            ['name' => 'Ireland', 'continent' => 'Europe', 'short_code' => 'IE', 'flag' => '🇮🇪'],
            ['name' => 'Italy', 'continent' => 'Europe', 'short_code' => 'IT', 'flag' => '🇮🇹'],
            ['name' => 'Kazakhstan', 'continent' => 'Europe', 'short_code' => 'KZ', 'flag' => '🇰🇿'],
            ['name' => 'Kosovo', 'continent' => 'Europe', 'short_code' => 'XK', 'flag' => '🇽🇰'],
            ['name' => 'Latvia', 'continent' => 'Europe', 'short_code' => 'LV', 'flag' => '🇱🇻'],
            ['name' => 'Liechtenstein', 'continent' => 'Europe', 'short_code' => 'LI', 'flag' => '🇱🇮'],
            ['name' => 'Lithuania', 'continent' => 'Europe', 'short_code' => 'LT', 'flag' => '🇱🇹'],
            ['name' => 'Luxembourg', 'continent' => 'Europe', 'short_code' => 'LU', 'flag' => '🇱🇺'],
            ['name' => 'Malta', 'continent' => 'Europe', 'short_code' => 'MT', 'flag' => '🇲🇹'],
            ['name' => 'Moldova', 'continent' => 'Europe', 'short_code' => 'MD', 'flag' => '🇲🇩'],
            ['name' => 'Monaco', 'continent' => 'Europe', 'short_code' => 'MC', 'flag' => '🇲🇨'],
            ['name' => 'Montenegro', 'continent' => 'Europe', 'short_code' => 'ME', 'flag' => '🇲🇪'],
            ['name' => 'Netherlands', 'continent' => 'Europe', 'short_code' => 'NL', 'flag' => '🇳🇱'],
            ['name' => 'North Macedonia', 'continent' => 'Europe', 'short_code' => 'MK', 'flag' => '🇲🇰'],
            ['name' => 'Norway', 'continent' => 'Europe', 'short_code' => 'NO', 'flag' => '🇳🇴'],
            ['name' => 'Poland', 'continent' => 'Europe', 'short_code' => 'PL', 'flag' => '🇵🇱'],
            ['name' => 'Portugal', 'continent' => 'Europe', 'short_code' => 'PT', 'flag' => '🇵🇹'],
            ['name' => 'Romania', 'continent' => 'Europe', 'short_code' => 'RO', 'flag' => '🇷🇴'],
            ['name' => 'Russia', 'continent' => 'Europe', 'short_code' => 'RU', 'flag' => '🇷🇺'],
            ['name' => 'San Marino', 'continent' => 'Europe', 'short_code' => 'SM', 'flag' => '🇸🇲'],
            ['name' => 'Serbia', 'continent' => 'Europe', 'short_code' => 'RS', 'flag' => '🇷🇸'],
            ['name' => 'Slovakia', 'continent' => 'Europe', 'short_code' => 'SK', 'flag' => '🇸🇰'],
            ['name' => 'Slovenia', 'continent' => 'Europe', 'short_code' => 'SI', 'flag' => '🇸🇮'],
            ['name' => 'Spain', 'continent' => 'Europe', 'short_code' => 'ES', 'flag' => '🇪🇸'],
            ['name' => 'Sweden', 'continent' => 'Europe', 'short_code' => 'SE', 'flag' => '🇸🇪'],
            ['name' => 'Switzerland', 'continent' => 'Europe', 'short_code' => 'CH', 'flag' => '🇨🇭'],
            ['name' => 'Turkey', 'continent' => 'Europe', 'short_code' => 'TR', 'flag' => '🇹🇷'],
            ['name' => 'Ukraine', 'continent' => 'Europe', 'short_code' => 'UA', 'flag' => '🇺🇦'],
            ['name' => 'United Kingdom', 'continent' => 'Europe', 'short_code' => 'GB', 'flag' => '🇬🇧'],
            ['name' => 'Vatican City', 'continent' => 'Europe', 'short_code' => 'VA', 'flag' => '🇻🇦'],
        ];

        $asianCountries = [
            ['name' => 'Afghanistan', 'continent' => 'Asia', 'short_code' => 'AF', 'flag' => '🇦🇫'],
            ['name' => 'Bahrain', 'continent' => 'Asia', 'short_code' => 'BH', 'flag' => '🇧🇭'],
            ['name' => 'Bangladesh', 'continent' => 'Asia', 'short_code' => 'BD', 'flag' => '🇧🇩'],
            ['name' => 'Bhutan', 'continent' => 'Asia', 'short_code' => 'BT', 'flag' => '🇧🇹'],
            ['name' => 'Brunei', 'continent' => 'Asia', 'short_code' => 'BN', 'flag' => '🇧🇳'],
            ['name' => 'Cambodia', 'continent' => 'Asia', 'short_code' => 'KH', 'flag' => '🇰🇭'],
            ['name' => 'China', 'continent' => 'Asia', 'short_code' => 'CN', 'flag' => '🇨🇳'],
            ['name' => 'India', 'continent' => 'Asia', 'short_code' => 'IN', 'flag' => '🇮🇳'],
            ['name' => 'Indonesia', 'continent' => 'Asia', 'short_code' => 'ID', 'flag' => '🇮🇩'],
            ['name' => 'Iran', 'continent' => 'Asia', 'short_code' => 'IR', 'flag' => '🇮🇷'],
            ['name' => 'Iraq', 'continent' => 'Asia', 'short_code' => 'IQ', 'flag' => '🇮🇶'],
            ['name' => 'Israel', 'continent' => 'Asia', 'short_code' => 'IL', 'flag' => '🇮🇱'],
            ['name' => 'Japan', 'continent' => 'Asia', 'short_code' => 'JP', 'flag' => '🇯🇵'],
            ['name' => 'Jordan', 'continent' => 'Asia', 'short_code' => 'JO', 'flag' => '🇯🇴'],
            ['name' => 'Kazakhstan', 'continent' => 'Asia', 'short_code' => 'KZ', 'flag' => '🇰🇿'],
            ['name' => 'Kuwait', 'continent' => 'Asia', 'short_code' => 'KW', 'flag' => '🇰🇼'],
            ['name' => 'Kyrgyzstan', 'continent' => 'Asia', 'short_code' => 'KG', 'flag' => '🇰🇬'],
            ['name' => 'Laos', 'continent' => 'Asia', 'short_code' => 'LA', 'flag' => '🇱🇦'],
            ['name' => 'Lebanon', 'continent' => 'Asia', 'short_code' => 'LB', 'flag' => '🇱🇧'],
            ['name' => 'Malaysia', 'continent' => 'Asia', 'short_code' => 'MY', 'flag' => '🇲🇾'],
            ['name' => 'Maldives', 'continent' => 'Asia', 'short_code' => 'MV', 'flag' => '🇲🇻'],
            ['name' => 'Mongolia', 'continent' => 'Asia', 'short_code' => 'MN', 'flag' => '🇲🇳'],
            ['name' => 'Myanmar', 'continent' => 'Asia', 'short_code' => 'MM', 'flag' => '🇲🇲'],
            ['name' => 'Nepal', 'continent' => 'Asia', 'short_code' => 'NP', 'flag' => '🇳🇵'],
            ['name' => 'North Korea', 'continent' => 'Asia', 'short_code' => 'KP', 'flag' => '🇰🇵'],
            ['name' => 'Oman', 'continent' => 'Asia', 'short_code' => 'OM', 'flag' => '🇴🇲'],
            ['name' => 'Pakistan', 'continent' => 'Asia', 'short_code' => 'PK', 'flag' => '🇵🇰'],
            ['name' => 'Palestine', 'continent' => 'Asia', 'short_code' => 'PS', 'flag' => '🇵🇸'],
            ['name' => 'Philippines', 'continent' => 'Asia', 'short_code' => 'PH', 'flag' => '🇵🇭'],
            ['name' => 'Qatar', 'continent' => 'Asia', 'short_code' => 'QA', 'flag' => '🇶🇦'],
            ['name' => 'Saudi Arabia', 'continent' => 'Asia', 'short_code' => 'SA', 'flag' => '🇸🇦'],
            ['name' => 'Singapore', 'continent' => 'Asia', 'short_code' => 'SG', 'flag' => '🇸🇬'],
            ['name' => 'South Korea', 'continent' => 'Asia', 'short_code' => 'KR', 'flag' => '🇰🇷'],
            ['name' => 'Sri Lanka', 'continent' => 'Asia', 'short_code' => 'LK', 'flag' => '🇱🇰'],
            ['name' => 'Syria', 'continent' => 'Asia', 'short_code' => 'SY', 'flag' => '🇸🇾'],
            ['name' => 'Tajikistan', 'continent' => 'Asia', 'short_code' => 'TJ', 'flag' => '🇹🇯'],
            ['name' => 'Thailand', 'continent' => 'Asia', 'short_code' => 'TH', 'flag' => '🇹🇭'],
            ['name' => 'Timor-Leste', 'continent' => 'Asia', 'short_code' => 'TL', 'flag' => '🇹🇱'],
            ['name' => 'Turkey', 'continent' => 'Asia', 'short_code' => 'TR', 'flag' => '🇹🇷'],
            ['name' => 'Turkmenistan', 'continent' => 'Asia', 'short_code' => 'TM', 'flag' => '🇹🇲'],
            ['name' => 'United Arab Emirates', 'continent' => 'Asia', 'short_code' => 'AE', 'flag' => '🇦🇪'],
            ['name' => 'Uzbekistan', 'continent' => 'Asia', 'short_code' => 'UZ', 'flag' => '🇺🇿'],
            ['name' => 'Vietnam', 'continent' => 'Asia', 'short_code' => 'VN', 'flag' => '🇻🇳'],
            ['name' => 'Yemen', 'continent' => 'Asia', 'short_code' => 'YE', 'flag' => '🇾🇪'],
        ];

        $africanCountries = [
            ['name' => 'Algeria', 'continent' => 'Africa', 'short_code' => 'DZ', 'flag' => '🇩🇿'],
            ['name' => 'Angola', 'continent' => 'Africa', 'short_code' => 'AO', 'flag' => '🇦🇴'],
            ['name' => 'Benin', 'continent' => 'Africa', 'short_code' => 'BJ', 'flag' => '🇧🇯'],
            ['name' => 'Botswana', 'continent' => 'Africa', 'short_code' => 'BW', 'flag' => '🇧🇼'],
            ['name' => 'Burkina Faso', 'continent' => 'Africa', 'short_code' => 'BF', 'flag' => '🇧🇫'],
            ['name' => 'Burundi', 'continent' => 'Africa', 'short_code' => 'BI', 'flag' => '🇧🇮'],
            ['name' => 'Cabo Verde', 'continent' => 'Africa', 'short_code' => 'CV', 'flag' => '🇨🇻'],
            ['name' => 'Cameroon', 'continent' => 'Africa', 'short_code' => 'CM', 'flag' => '🇨🇲'],
            ['name' => 'Central African Republic', 'continent' => 'Africa', 'short_code' => 'CF', 'flag' => '🇨🇫'],
            ['name' => 'Chad', 'continent' => 'Africa', 'short_code' => 'TD', 'flag' => '🇹🇩'],
            ['name' => 'Comoros', 'continent' => 'Africa', 'short_code' => 'KM', 'flag' => '🇰🇲'],
            ['name' => 'Congo (Congo-Brazzaville)', 'continent' => 'Africa', 'short_code' => 'CG', 'flag' => '🇨🇬'],
            ['name' => 'Congo (DRC)', 'continent' => 'Africa', 'short_code' => 'CD', 'flag' => '🇨🇩'],
            ['name' => 'Djibouti', 'continent' => 'Africa', 'short_code' => 'DJ', 'flag' => '🇩🇯'],
            ['name' => 'Egypt', 'continent' => 'Africa', 'short_code' => 'EG', 'flag' => '🇪🇬'],
            ['name' => 'Equatorial Guinea', 'continent' => 'Africa', 'short_code' => 'GQ', 'flag' => '🇬🇶'],
            ['name' => 'Eritrea', 'continent' => 'Africa', 'short_code' => 'ER', 'flag' => '🇪🇷'],
            ['name' => 'Eswatini', 'continent' => 'Africa', 'short_code' => 'SZ', 'flag' => '🇸🇿'],
            ['name' => 'Ethiopia', 'continent' => 'Africa', 'short_code' => 'ET', 'flag' => '🇪🇹'],
            ['name' => 'Gabon', 'continent' => 'Africa', 'short_code' => 'GA', 'flag' => '🇬🇦'],
            ['name' => 'Gambia', 'continent' => 'Africa', 'short_code' => 'GM', 'flag' => '🇬🇲'],
            ['name' => 'Ghana', 'continent' => 'Africa', 'short_code' => 'GH', 'flag' => '🇬🇭'],
            ['name' => 'Guinea', 'continent' => 'Africa', 'short_code' => 'GN', 'flag' => '🇬🇳'],
            ['name' => 'Guinea-Bissau', 'continent' => 'Africa', 'short_code' => 'GW', 'flag' => '🇬🇼'],
            ['name' => 'Ivory Coast', 'continent' => 'Africa', 'short_code' => 'CI', 'flag' => '🇨🇮'],
            ['name' => 'Kenya', 'continent' => 'Africa', 'short_code' => 'KE', 'flag' => '🇰🇪'],
            ['name' => 'Lesotho', 'continent' => 'Africa', 'short_code' => 'LS', 'flag' => '🇱🇸'],
            ['name' => 'Liberia', 'continent' => 'Africa', 'short_code' => 'LR', 'flag' => '🇱🇷'],
            ['name' => 'Libya', 'continent' => 'Africa', 'short_code' => 'LY', 'flag' => '🇱🇾'],
            ['name' => 'Madagascar', 'continent' => 'Africa', 'short_code' => 'MG', 'flag' => '🇲🇬'],
            ['name' => 'Malawi', 'continent' => 'Africa', 'short_code' => 'MW', 'flag' => '🇲🇼'],
            ['name' => 'Mali', 'continent' => 'Africa', 'short_code' => 'ML', 'flag' => '🇲🇱'],
            ['name' => 'Mauritania', 'continent' => 'Africa', 'short_code' => 'MR', 'flag' => '🇲🇷'],
            ['name' => 'Mauritius', 'continent' => 'Africa', 'short_code' => 'MU', 'flag' => '🇲🇺'],
            ['name' => 'Morocco', 'continent' => 'Africa', 'short_code' => 'MA', 'flag' => '🇲🇦'],
            ['name' => 'Mozambique', 'continent' => 'Africa', 'short_code' => 'MZ', 'flag' => '🇲🇿'],
            ['name' => 'Namibia', 'continent' => 'Africa', 'short_code' => 'NA', 'flag' => '🇳🇦'],
            ['name' => 'Niger', 'continent' => 'Africa', 'short_code' => 'NE', 'flag' => '🇳🇪'],
            ['name' => 'Nigeria', 'continent' => 'Africa', 'short_code' => 'NG', 'flag' => '🇳🇬'],
            ['name' => 'Rwanda', 'continent' => 'Africa', 'short_code' => 'RW', 'flag' => '🇷🇼'],
            ['name' => 'Sao Tome and Principe', 'continent' => 'Africa', 'short_code' => 'ST', 'flag' => '🇸🇹'],
            ['name' => 'Senegal', 'continent' => 'Africa', 'short_code' => 'SN', 'flag' => '🇸🇳'],
            ['name' => 'Seychelles', 'continent' => 'Africa', 'short_code' => 'SC', 'flag' => '🇸🇨'],
            ['name' => 'Sierra Leone', 'continent' => 'Africa', 'short_code' => 'SL', 'flag' => '🇸🇱'],
            ['name' => 'Somalia', 'continent' => 'Africa', 'short_code' => 'SO', 'flag' => '🇸🇴'],
            ['name' => 'South Africa', 'continent' => 'Africa', 'short_code' => 'ZA', 'flag' => '🇿🇦'],
            ['name' => 'South Sudan', 'continent' => 'Africa', 'short_code' => 'SS', 'flag' => '🇸🇸'],
            ['name' => 'Sudan', 'continent' => 'Africa', 'short_code' => 'SD', 'flag' => '🇸🇩'],
            ['name' => 'Tanzania', 'continent' => 'Africa', 'short_code' => 'TZ', 'flag' => '🇹🇿'],
            ['name' => 'Togo', 'continent' => 'Africa', 'short_code' => 'TG', 'flag' => '🇹🇬'],
            ['name' => 'Tunisia', 'continent' => 'Africa', 'short_code' => 'TN', 'flag' => '🇹🇳'],
            ['name' => 'Uganda', 'continent' => 'Africa', 'short_code' => 'UG', 'flag' => '🇺🇬'],
            ['name' => 'Zambia', 'continent' => 'Africa', 'short_code' => 'ZM', 'flag' => '🇿🇲'],
            ['name' => 'Zimbabwe', 'continent' => 'Africa', 'short_code' => 'ZW', 'flag' => '🇿🇼'],
        ];

        $northAmericanCountries = [
            ['name' => 'Antigua and Barbuda', 'continent' => 'North America', 'short_code' => 'AG', 'flag' => '🇦🇬'],
            ['name' => 'Bahamas', 'continent' => 'North America', 'short_code' => 'BS', 'flag' => '🇧🇸'],
            ['name' => 'Barbados', 'continent' => 'North America', 'short_code' => 'BB', 'flag' => '🇧🇧'],
            ['name' => 'Belize', 'continent' => 'North America', 'short_code' => 'BZ', 'flag' => '🇧🇿'],
            ['name' => 'Canada', 'continent' => 'North America', 'short_code' => 'CA', 'flag' => '🇨🇦'],
            ['name' => 'Costa Rica', 'continent' => 'North America', 'short_code' => 'CR', 'flag' => '🇨🇷'],
            ['name' => 'Cuba', 'continent' => 'North America', 'short_code' => 'CU', 'flag' => '🇨🇺'],
            ['name' => 'Dominica', 'continent' => 'North America', 'short_code' => 'DM', 'flag' => '🇩🇲'],
            ['name' => 'Dominican Republic', 'continent' => 'North America', 'short_code' => 'DO', 'flag' => '🇩🇴'],
            ['name' => 'El Salvador', 'continent' => 'North America', 'short_code' => 'SV', 'flag' => '🇸🇻'],
            ['name' => 'Grenada', 'continent' => 'North America', 'short_code' => 'GD', 'flag' => '🇬🇩'],
            ['name' => 'Guatemala', 'continent' => 'North America', 'short_code' => 'GT', 'flag' => '🇬🇹'],
            ['name' => 'Haiti', 'continent' => 'North America', 'short_code' => 'HT', 'flag' => '🇭🇹'],
            ['name' => 'Honduras', 'continent' => 'North America', 'short_code' => 'HN', 'flag' => '🇭🇳'],
            ['name' => 'Jamaica', 'continent' => 'North America', 'short_code' => 'JM', 'flag' => '🇯🇲'],
            ['name' => 'Mexico', 'continent' => 'North America', 'short_code' => 'MX', 'flag' => '🇲🇽'],
            ['name' => 'Nicaragua', 'continent' => 'North America', 'short_code' => 'NI', 'flag' => '🇳🇮'],
            ['name' => 'Panama', 'continent' => 'North America', 'short_code' => 'PA', 'flag' => '🇵🇦'],
            ['name' => 'Saint Kitts and Nevis', 'continent' => 'North America', 'short_code' => 'KN', 'flag' => '🇰🇳'],
            ['name' => 'Saint Lucia', 'continent' => 'North America', 'short_code' => 'LC', 'flag' => '🇱🇨'],
            [
                'name' => 'Saint Vincent and the Grenadines', 'continent' => 'North America', 'short_code' => 'VC',
                'flag' => '🇻🇨',
            ],
            ['name' => 'Trinidad and Tobago', 'continent' => 'North America', 'short_code' => 'TT', 'flag' => '🇹🇹'],
            ['name' => 'United States', 'continent' => 'North America', 'short_code' => 'US', 'flag' => '🇺🇸'],
        ];

        $southAmericanCountries = [
            ['name' => 'Argentina', 'continent' => 'South America', 'short_code' => 'AR', 'flag' => '🇦🇷'],
            ['name' => 'Bolivia', 'continent' => 'South America', 'short_code' => 'BO', 'flag' => '🇧🇴'],
            ['name' => 'Brazil', 'continent' => 'South America', 'short_code' => 'BR', 'flag' => '🇧🇷'],
            ['name' => 'Chile', 'continent' => 'South America', 'short_code' => 'CL', 'flag' => '🇨🇱'],
            ['name' => 'Colombia', 'continent' => 'South America', 'short_code' => 'CO', 'flag' => '🇨🇴'],
            ['name' => 'Ecuador', 'continent' => 'South America', 'short_code' => 'EC', 'flag' => '🇪🇨'],
            ['name' => 'Guyana', 'continent' => 'South America', 'short_code' => 'GY', 'flag' => '🇬🇾'],
            ['name' => 'Paraguay', 'continent' => 'South America', 'short_code' => 'PY', 'flag' => '🇵🇾'],
            ['name' => 'Peru', 'continent' => 'South America', 'short_code' => 'PE', 'flag' => '🇵🇪'],
            ['name' => 'Suriname', 'continent' => 'South America', 'short_code' => 'SR', 'flag' => '🇸🇷'],
            ['name' => 'Uruguay', 'continent' => 'South America', 'short_code' => 'UY', 'flag' => '🇺🇾'],
            ['name' => 'Venezuela', 'continent' => 'South America', 'short_code' => 'VE', 'flag' => '🇻🇪'],
        ];

        $oceaniaCountries = [
            ['name' => 'Australia', 'continent' => 'Oceania', 'short_code' => 'AU', 'flag' => '🇦🇺'],
            ['name' => 'Fiji', 'continent' => 'Oceania', 'short_code' => 'FJ', 'flag' => '🇫🇯'],
            ['name' => 'Kiribati', 'continent' => 'Oceania', 'short_code' => 'KI', 'flag' => '🇰🇮'],
            ['name' => 'Marshall Islands', 'continent' => 'Oceania', 'short_code' => 'MH', 'flag' => '🇲🇭'],
            ['name' => 'Micronesia', 'continent' => 'Oceania', 'short_code' => 'FM', 'flag' => '🇫🇲'],
            ['name' => 'Nauru', 'continent' => 'Oceania', 'short_code' => 'NR', 'flag' => '🇳🇷'],
            ['name' => 'New Zealand', 'continent' => 'Oceania', 'short_code' => 'NZ', 'flag' => '🇳🇿'],
            ['name' => 'Palau', 'continent' => 'Oceania', 'short_code' => 'PW', 'flag' => '🇵🇼'],
            ['name' => 'Papua New Guinea', 'continent' => 'Oceania', 'short_code' => 'PG', 'flag' => '🇵🇬'],
            ['name' => 'Samoa', 'continent' => 'Oceania', 'short_code' => 'WS', 'flag' => '🇼🇸'],
            ['name' => 'Solomon Islands', 'continent' => 'Oceania', 'short_code' => 'SB', 'flag' => '🇸🇧'],
            ['name' => 'Tonga', 'continent' => 'Oceania', 'short_code' => 'TO', 'flag' => '🇹🇴'],
            ['name' => 'Tuvalu', 'continent' => 'Oceania', 'short_code' => 'TV', 'flag' => '🇹🇻'],
            ['name' => 'Vanuatu', 'continent' => 'Oceania', 'short_code' => 'VU', 'flag' => '🇻🇺'],
        ];

        collect($europeanCountries)->merge($asianCountries)->merge($africanCountries)->merge($oceaniaCountries)
            ->merge($northAmericanCountries)->merge($southAmericanCountries)
            ->each(fn (array $data) => Country::query()->updateOrCreate(['name' => $data['name']], array_merge($data, [
                'created_by' => 1,
                'updated_by' => 1,
            ])));
    }
}
