services:
  app:
    build:
      context: ../Stubs
      network: host
      dockerfile: ./.docker/Dockerfile
      args:
        UID: ${DOCKER_UID}
        USER: ${DOCKER_USERNAME}
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_IMAGE_NAME}-app
    restart: unless-stopped
    command: php-fpm -F
    working_dir: /
    extra_hosts:
      - "thishost:172.17.0.1"
    depends_on:
      - redis
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - default
  horizon:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_IMAGE_NAME}-horizon
    depends_on:
      - app
    restart: unless-stopped
    user: ${DOCKER_WWW_DATA:-33}
    working_dir: /
    command: php artisan horizon
    extra_hosts:
      - "thishost:172.17.0.1"
    volumes:
      - ./:/app:delegated
    networks:
      - default
  reverb:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_IMAGE_NAME}-reverb
    depends_on:
      - app
    restart: unless-stopped
    user: ${DOCKER_WWW_DATA:-33}
    working_dir: /
    command: php artisan reverb:start
    ports:
      - ${REVERB_PORT}:${REVERB_SERVER_PORT}
    extra_hosts:
      - "thishost:172.17.0.1"
    volumes:
      - ./:/app:delegated
    networks:
      - default
  cron:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_IMAGE_NAME}-cron
    depends_on:
      - app
    restart: unless-stopped
    extra_hosts:
      - "thishost:172.17.0.1"
    working_dir: /
    command: cron -f
    volumes:
      - ./:/app:delegated
    networks:
      - default
  server:
    image: nginx:alpine
    container_name: ${DOCKER_IMAGE_NAME}-server
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - ${DOCKER_NGINX_PORT}:80
    environment:
      APP_HOST: ${DOCKER_IMAGE_NAME}-app
    volumes:
      - ./:/app:delegated
      - ./.docker/config/appserver.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - default
  redis:
    image: "redis:alpine"
    container_name: ${DOCKER_IMAGE_NAME}-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - default
volumes:
  redis-data:
    external: false
networks:
  default:
    external: true
    name: ${DOCKER_NETWORK_NAME:-network}
